name: Build example projects 
on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  LaTeX:
    name: build LaTex project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: install builbo
        run: |
          sudo make install-cli
      - name: install git
        run: |
          sudo apt-get install -y git
      - name: check out example repo
        run: |
          cd
          git clone https://github.com/obnoxxx/latex-doc-example.git
          cd latex-doc-example
      - name: debug info
        run: pwd
      - name: build in builbo
        run: |
          builbo -l latex -o suse -b -s "make doc"

  tinyproxy:
    name: build tinyproxy C  project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: install builbo
        run: |
          sudo make install-cli
      - name: install git
        run: |
          sudo apt-get install -y git
      - name: check out tinyproxy repo
        run: |
          cd
          git clone https://github.com/tinyproxy/tinyproxy.git
          cd tinyproxy
      - name: debug info
        run: |
          pwd
          ls -l
      - name: build in builbo
        run: |
          builbo -l c -o fedora  -b -s "./autogen.sh && make"

